# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>

test:
  secret_key_base: 57ea07e1d98780bb77b48f8aad5641f7d1237c1854200d7958bdddb5536416dae26b53b39b5025a6e3d6cc5cae541f4007608cd1a25179b1651d332e8eeef425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>
